default:
	@echo "list    -- Recursively list all files larger than a threshold"
	@echo "small   -- Compress all those files larger than a threshold"
	@echo "restore -- Uncompress all those files compressed using make small"
	
list:
	@./createlist.sh   # Execute scripts
small:
	@./compress.sh
restore:
	@./restore.sh
	

